services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment:
        - SUPABASE_URL=https://cfqcaayrywfljslbdkfi.supabase.co
        - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcWNhYXlyeXdmbGpzbGJka2ZpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDYyNDUwMCwiZXhwIjoyMDUwMjAwNTAwfQ.zSxB4vnqgIwaz8z6K3kTTp-foli9283soDGn8QxF92E
      ports:
        - "8081:80"
        
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"