services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/backend
      - APP_ENV=development
      - SUPABASE_URL=
      - SUPABASE_SERVICE_KEY=
    expose:
      - "8000"
    networks:
      - wishcraft-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - "3000"
    networks:
      - wishcraft-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "443:443"
      - "80:80"
    networks:
      - wishcraft-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./webroot:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./webroot:/var/www/certbot
    # Create the SSL Certificate
    # command: >
      # certonly --webroot
      # --webroot-path=/var/www/certbot
      # --email ${EMAIL}
      # --agree-tos
      # --no-eff-email
      # -d ${DOMAIN}
      # -d www.${DOMAIN}
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot-path=/var/www/certbot && sleep 12h; done"
    networks:
      - wishcraft-network

networks:
  wishcraft-network:
    driver: bridge