services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - SUPABASE_URL=
      - SUPABASE_SERVICE_KEY=
    expose:
      - "8080"
    networks:
      - wishcraft-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - "3000"
    networks:
      - wishcraft-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
networks:
  wishcraft-network:
    driver: bridge