# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the Nginx configuration file into the container
COPY nginx.local.conf /etc/nginx/conf.d/default.conf

# Expose HTTP port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]